baseURL: https://kinoite.fedoraproject.org/
canonifyURLs: true
defaultContentLanguage: en
disableKinds:
- taxonomy
- term
enableGitInfo: true
enableRobotsTXT: true
i18n:
  content:
    default:
      files:
      - content/_index.md
      - content/get-involved.md
      - content/download/_index.md
  excludedKeys: changelog class color figure hero_image image images licenses link
    logo major_version peertube release src url version version_text video youtube
  genToOtherDir: true
  langs: ast ca ca@valencia cs de es et eu fi fr gl hu it ko nl pt pt_BR ru sk sv
    tr uk zh_CN
  others:
  - strings
languages:
  en:
    contentDir: content/
    languageCode: en
    languageName: English
    weight: 1
  fr:
    contentDir: content-trans/fr
    languageCode: fr
    languageName: Français
    weight: 2
  uk:
    contentDir: content-trans/uk
    languageCode: uk
    languageName: Українська
    weight: 2
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
module:
  imports:
  - mounts:
    - source: sass
      target: assets/sass/bulma
    path: github.com/jgthms/bulma
outputs:
  home:
  - HTML
  - RSS
  section:
  - HTML
params:
  description: Fedora Kinoite is an immutable desktop operating system featuring the
    KDE Plasma desktop
  images:
  - /thumbnail.png
  title: Fedora Kinoite
rssLimit: 4
summaryLength: 15
