baseURL: https://kinoite.fedoraproject.org/
canonifyURLs: true
defaultContentLanguage: en
disableKinds:
- taxonomy
- term
enableGitInfo: true
enableRobotsTXT: true
i18n:
  content:
    kinoite-fedoraproject-org:
      files:
      - content/_index.md
      - content/get-involved.md
      - content/download/_index.md
  excludedKeys: changelog class color figure hero_image image images licenses link
    logo major_version peertube release src url version version_text video youtube
  genToOtherDir: true
  langs: ast ca ca@valencia cs de es et eu fi fr gl hu it ko nl pt pt_BR ru sk sv
    tr uk zh_CN
  others:
  - strings
languages:
  en:
    contentDir: content/
    languageCode: en
    languageName: English
    menu:
      main:
      - name: Download
        url: /download
        weight: 1
      - name: Get Involved
        url: /get-involved
        weight: 2
      - name: Docs
        url: https://docs.fedoraproject.org/en-US/fedora-kinoite/
        weight: 3
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
module:
  imports:
  - mounts:
    - source: sass
      target: assets/sass/bulma
    path: github.com/jgthms/bulma
outputs:
  home:
  - HTML
  - RSS
  section:
  - HTML
params:
  description: Fedora Kinoite is an immutable desktop operating system featuring the KDE Plasma desktop
  images:
  - /thumbnail.png
  title: Fedora Kinoite
rssLimit: 4
summaryLength: 15
